---
settingsVersion: '1.66'
exclusionRules:
- pattern: "https?://mail.google.com/*"
  passKeys: ''
- pattern: "https?://github.com/*"
  passKeys: t
- pattern: "https?://gitlab.com/*"
  passKeys: t
filterLinkHints: false
waitForEnterForFilteredHints: true
hideHud: false
keyMappings: |-
  map h goBack
  map l goForward
  map H previousTab
  map L nextTab
  map i LinkHints.activateMode
  map I LinkHints.activateModeToOpenInNewTab
  map gg scrollToTop
  map G scrollToBottom
  map x removeTab
  map u restoreTab
  map p openCopiedUrlInNewTab
  map yy copyCurrentUrl
  map <c-f> scrollFullPageDown
  map <c-b> scrollFullPageUp
linkHintCharacters: sadfjklewcmpgh
linkHintNumbers: '0123456789'
newTabUrl: about:newtab
nextPatterns: next,more,newer,>,›,→,»,≫,>>
previousPatterns: prev,previous,back,older,<,‹,←,«,≪,<<
regexFindMode: false
ignoreKeyboardLayout: false
scrollStepSize: 60
smoothScroll: true
grabBackFocus: true
searchEngines: |-
  w: https://www.wikipedia.org/w/index.php?title=Special:Search&search=%s Wikipedia

  # More examples.
  #
  # (Vimium supports search completion Wikipedia, as
  # above, and for these.)
  #
  # g: https://www.google.com/search?q=%s Google
  # l: https://www.google.com/search?q=%s&btnI I'm feeling lucky...
  # y: https://www.youtube.com/results?search_query=%s Youtube
  # gm: https://www.google.com/maps?q=%s Google maps
  # b: https://www.bing.com/search?q=%s Bing
  # d: https://duckduckgo.com/?q=%s DuckDuckGo
  # az: https://www.amazon.com/s/?field-keywords=%s Amazon
  # qw: https://www.qwant.com/?q=%s Qwant
searchUrl: "https://www.google.com/search?q="
userDefinedLinkHintCss: |-
  div > .vimiumHintMarker {
    /* linkhint boxes */
    background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#FFF785),
    color-stop(100%,#FFC542));
    border: 1px solid #E3BE23;
  }

  div > .vimiumHintMarker span {
    /* linkhint text */
    color: black;
    font-weight: bold;
    font-size: 12px;
  }

  div > .vimiumHintMarker > .matchingCharacter {}
